### ISSUE TITLE
CI (Continuous Integration) Proposal: Consolidate Documenter and Test GitHub Actions workflows into a single CI workflow

### ISSUE THREAD

**Issue by ktchu** [JuliaGeometricAlgebra/GeometricAlgebra.jl#3]
The GitHub Actions workflows generated by the PkgTemplate package now includes a CI.yml workflows file that consolidates test and documentation generation, so it seems reasonable to combine the Documenter and Test workflows into a single CI workflow to follow the current Julia packaging trend.

Thoughts?

If we would like to proceed in this direction, I have a customized version of CI.yml that makes a few improvements to the default CI.yml, such as

* generation of release-specific documentation and

* improved efficiency by loading of code coverage data to Codecov for only a single configuration of the job matrix.

**Comment by serenity4** [comment]
No objections against that from my side. Feel free to submit a PR.
