### ISSUE TITLE
Proposal. Configure branch protection rules for "main".

### ISSUE THREAD

**Issue by ktchu** [JuliaGeometricAlgebra/GeometricAlgebra.jl#6]
To help keep "main" relatively stable between official releases, I'd like to propose we configure the GitHub repository so that "main" has the following branch protection rules.

* Require a pull before merging
  * Require 1 approval before pull requests can be merged.

* Include administrators

**Comment by serenity4** [comment]
I agree with your proposal. Feel free to configure the repo once you have been given the proper accesses (see [this discussion](https://github.com/orgs/JuliaGeometricAlgebra/teams/organization-founders/discussions/1) in that regard).

**Comment by serenity4** [comment]
I went ahead with the changes. I now need your approval (or someone else's) on #8.
