### ISSUE TITLE
Proposal. Adopt the "Reviewing, Approving and Merging PRs" procedure from ColPrac

### ISSUE THREAD

**Issue by ktchu** [JuliaGeometricAlgebra/GeometricAlgebra.jl#7]
As a procedure for approving and merging pull requests, what does everything think about using something like the "Reviewing, Approving and Merging PRs" procedure suggested by the [ColPrac guidelines](https://colprac.sciml.ai/).

I have been using this procedure for a couple of my projects (including the one that William and I are working on) and have found it to be easy to use, relatively efficient, and good for facilitating collaboration between contributors who are working asynchronously (i.e., not all at the same location, working at the same time, etc.).

**Comment by serenity4** [comment]
Closed via #8.
